version: "3"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud_postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data