version: "3"
services:
  crud:
    container_name: "crud_poc"
    image: dchristofolli/crud
    ports: 
      - '8080:8080'
    depends_on: 
      - mongo
  mongo:
    container_name: "crud-mongo"
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - './mongo-data:/data/db'
  mongo-express:
    container_name: "crud-mongoe"
    image: mongo-express
    ports:
      - '8081:8081'
    depends_on:
      - mongo
