server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_crud
      auto-index-creation: false
rabbitmq:
  queueName: spring-boot
  exchangeName: spring-boot-exchange
  routingKey: foo.bar.#