server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_crud
      auto-index-creation: false
rabbitmq:
  specificQueueName: specific
  responseQueueName: response
  exchangeName: spring-boot-exchange
  listAllExchange: all-users-exchange
  routingKey: foo.bar.#
  findAllRoutingKey: app.users